/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pokedemo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.*;
import java.net.HttpCookie;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

public class App {
    public static void main(String[] args) throws IOException
    {
        // 1. Make a URL to talk to a website
        // *** Show bad URL ***
        URL pokeUrl = new URL("https://pokeapi.co/api/v2/pokemon/ditto");
        // 2. Make a connection to the website
        HttpURLConnection pokeUrlConnection = (HttpURLConnection) pokeUrl.openConnection();
        // 3. Specify a method for our connection
        pokeUrlConnection.setRequestMethod("GET");
        // 4. Need to read from this connection
        InputStreamReader pokeInputStreamReader = new InputStreamReader(pokeUrlConnection.getInputStream());
        BufferedReader pokeBufferedReader = new BufferedReader(pokeInputStreamReader);
        String pokeData = pokeBufferedReader.readLine();
        System.out.println(pokeData);
        // 5. Need convert format to objects
        // 5 1/2. Make objects for the data to live in
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        Pokemon ditto = gson.fromJson(pokeData, Pokemon.class);
        // In your lab:
        // If getting internet quote, read from a file too, append to that file
        // 6. Write file out to disk
        File dittoFile = new File("./ditto.json");
        try(FileWriter dittoFileWriter = new FileWriter(dittoFile))
        {
            gson.toJson(ditto, dittoFileWriter);
        }
    }
}
