/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alice;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Scanner;

public class App {
    public static void main(String[] args) throws IOException {
      // read each line of Alice and Wonderland and determine how many times the word Alice comes up
      Path alicePath = Path.of("alice_in_wonderland.txt");
      System.out.println(alicePath.toAbsolutePath());

      // Read the File - Scanner
      Scanner scanner = null;
      scanner = new Scanner(alicePath);

      // Create HashMap before reading text
      String characterName = "Alice";
      HashMap<String, Integer> aliceMap = new HashMap<>();
      aliceMap.put(characterName, 0);

      while(scanner.hasNextLine()) {
        // Check every line for Alice
        String currentLine = scanner.nextLine();
        if(currentLine.contains(characterName)) {
          // If any instances, add to the HashMap
          int newValue = aliceMap.get(characterName) + 1;
          aliceMap.put(characterName, newValue);
          // 1 line for updating hashMap
          // aliceMap.put(characterName, aliceMap.get(characterName) + 1);
        }
      }

      System.out.println("Alice showed up in " + aliceMap.get(characterName) + " lines.");

      // BUFFERED READER EXAMPLE
      BufferedReader reader = null;
      try {
        reader = Files.newBufferedReader(alicePath);
        String line = reader.readLine();
        // check for adding to Alice map here
        while (line != null) {
          line = reader.readLine();
          // check for adding to Alice map after reaching each line here
        }
      } catch(IOException ioe) {
        System.out.println("Error reading file: " + ioe.getMessage());
        ioe.printStackTrace();
      } finally {
        reader.close();
      }

      // THIS IS BEST APPROACH IF USING BUFFERED READER (TRY W/ RESOURCES)
      try(BufferedReader resourceReader = Files.newBufferedReader(alicePath)) {
        String resourceLine = resourceReader.readLine();
        // check for adding to Alice map here
        while(resourceLine != null) {
          resourceLine = resourceReader.readLine();
          // check for adding to Alice map after reaching each line here
        }
      } catch (IOException ioe) {
        System.out.println("Error reading file: " + ioe.getMessage());
        ioe.printStackTrace();
      }
    }
}
