/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package studentAttendance;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;

public class StudentAttendance
{
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)
    {
        ArrayList<Boolean> hasAttended = new ArrayList<>();
        hasAttended.add(true);
        hasAttended.add(false);
        hasAttended.add(true);

        // Attendance -- how do we map? String and boolean

        HashMap<String, ArrayList<Boolean>> dailyAttendance = new HashMap<>();
        HashSet<String> classStudents = new HashSet<String>();

        ArrayList<String> students = new ArrayList<>();
        students.add("Shan");
        students.add("Brandon");
        classStudents.addAll(students);

        dailyAttendance.put("Ed", hasAttended);

        //Integer attendanceInstances = dailyAttendance.get("Ed");
        /*if(dailyAttendance.containsKey("Ed") == false)
        {
            dailyAttendance.put("Ed", 1);
        }
        else
        {
            dailyAttendance.put("Ed", dailyAttendance.get("Ed") + 1);
        }*/

        System.out.println("Ed's times attended: " + dailyAttendance.get("Ed"));
        System.out.println("Students: " + classStudents);
    }
}
