/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import critters.BadCritterException;
import critters.Cat;
import critters.Critter;
import critters.Robot;
import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void critterTestWorksWithCats() {
        Critter c = Critter.parse("Cat");

        // instanceof is how we know the critter is of type Cat
        assertTrue(c instanceof Cat);
        assertFalse(c instanceof Robot);
    }

    @Test
    public void critterTestWorksWithRobots() {

    }

    @Test
    public void critterTestThrowsOnFailure() {
        try {
            // we want to test a failure
            // Critter.parse will fail and throw
            // and then _skip_ the fail() (jumping to the catch)
            Critter c = Critter.parse("BAD DOG");

            // this line will only happen if the parse was successful!
            fail("Critter was created!  That's wrong!");
        } catch (Exception ex) {
            // assert that we have the correct type of exception
            assertTrue(ex instanceof BadCritterException);
        }
    }
}
