/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gsonicorns;

import com.google.gson.Gson;

import java.io.*;
import java.util.ArrayList;

public class App {
  public static void main(String[] args) throws FileNotFoundException {
    // writing primitives with GSON (serialization)
    Gson gson = new Gson();
    int foo = 1;
    gson.toJson(foo); // ==> 1
    String bar = "abcd";
    gson.toJson(bar); // ==> \"abcbd\"
    int[] values = {1, 2, 3, 4, 5};
    gson.toJson(values); // ==> [1,2,3,4,5]

    // fromJson to Java --> need a type (deserialization)
    String stringyArray = "[\"Blue\",\"Green\",\"Purple\"]";

    int one = gson.fromJson("1", int.class);
    boolean notTrue = gson.fromJson("false", boolean.class);
    String[] strArray1 = gson.fromJson("[\"abc\"]", String[].class);
    String[] strArray2 = gson.fromJson(stringyArray, String[].class);

    //OBJECTS
    ArrayList<String> colors = new ArrayList<>();
    colors.add("white");
    colors.add("pink");
    // create a unicorn object and convert it to JSON
    Unicorn unicorn = new Unicorn(colors, true, 4, 5);
    String jsonicorn = gson.toJson(unicorn);
    System.out.println(jsonicorn);

    String darkicorn = "{\"hornLength\":20,\"isMajestic\":true,\"colors\":[\"Grey\",\"Black\"]}";
    Unicorn darkicornRevivied = gson.fromJson(darkicorn, Unicorn.class);
    System.out.println(darkicorn);
    System.out.println(darkicornRevivied.toString());

    // Write JSON to File
    File unicornFileOut = new File("./app/src/main/resources/unicorn.json");
    try(FileWriter unicornFileWriter = new FileWriter(unicornFileOut)) {
      gson.toJson(darkicornRevivied, unicornFileWriter);
      System.out.println("test");
    } catch(IOException ioe) {
      System.out.println("Caught an IOException with stack trace: ");
      ioe.printStackTrace();
    }

    // Read from a JSON file
    File unicornFile = new File("./app/src/main/resources/unicorn.json");
    FileReader unicornFileReader = new FileReader(unicornFile);
    Unicorn darkicornTwo = gson.fromJson(unicornFileReader, Unicorn.class);
    System.out.println(darkicornTwo);
  }
}
