/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jsonquotes;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Collection;

public class App {
  public static void main(String[] args) throws FileNotFoundException {
    // grab gson (to read json files)
    // read all our quotes from a json file
    // place all the quotes into an array
    // randomly select one quote and print its author/text to the screen

    Gson gson = new Gson();
    FileReader myFile = new FileReader("./app/src/main/resources/recentQuotes.json");

    // using an array
    // Quote[] quotes = gson.fromJson(myFile, Quote[].class);
    // // rather than picking a random quote, we've just returned the first
    // System.out.println(quotes[0].getAuthor() + " : " + quotes[0].getText());

    // using an arrayList (TypeToken)
    TypeToken<ArrayList<Quote>> collectionType = new TypeToken<ArrayList<Quote>>(){};
    ArrayList<Quote> quotesList = gson.fromJson(myFile, collectionType);

    System.out.println(quotesList.get(0).getAuthor() + " : " + quotesList.get(0).getText());

  }
}
