/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package swapi;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

public class App {

  public static void main(String[] args) throws IOException {
    // step 1: create url. and an HttpURLConnection
    URL starURL = new URL("https://www.swapi.tech/api/people/1");
    HttpURLConnection starConnection = (HttpURLConnection) starURL.openConnection();

    // step 2: set our headers, check response code, use a try/catch to handle bad urls + close connection
    try {
      starConnection.setRequestMethod("GET");
      int starStatus = starConnection.getResponseCode();
      System.out.println(starStatus);

      if(starStatus == 200) {
        // do some stuff

        // step 3: get data as a stream
        InputStreamReader starStreamReader = new InputStreamReader(starConnection.getInputStream());

        // step 4: use BufferedReader to read the input (can also use starStreamReader.read())
        try(BufferedReader starBufferedReader = new BufferedReader(starStreamReader)) {
          String line = starBufferedReader.readLine();
          System.out.println(line);

          // step 5 part 1: create class(es) to convert formatted JSON into Java objects (come back here when you're
          // done)
          // step 5 part 2: use GSON to create your Java objects
          Gson gson = new Gson();
          StarWarsPerson starWarsPerson = gson.fromJson(line, StarWarsPerson.class);
          System.out.println(starWarsPerson);
        }
      }

    } catch(MalformedURLException mue) {
      System.out.println("bad url");
      mue.printStackTrace();
    } catch(IOException ioe) {
      System.out.println("problem with api");
      ioe.printStackTrace();
    } finally {
      starConnection.disconnect();
    }
  }
}
