/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animalResort;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Bear bear = new Bear();
        Sloth sloth = new Sloth();
        Aardvark aardvark = new Aardvark();

        List<Animal> resortAnimals = new ArrayList<>();
        resortAnimals.add(bear);
        resortAnimals.add(sloth);
        resortAnimals.add(aardvark);

        //Animal animalThatIsABear = resortAnimals.get(0);

        Animal animal = bear;
        //Animal testAnimal = new Animal();

        //Bear sameBear = (Bear)animalThatIsABear;

        /*if (animal instanceof Bear)
        {
            bear = (Bear) animal;
        }*/

        String dollarSign = "$";
        String fourDollarSigns = dollarSign.repeat(4);

        Bear sameBear = (Bear)animal;

        System.out.print("This bear says: ");
        animal.noise();
    }
}
