/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package studentAttendance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StudentAttendanceTest
{
    @Test void appHasAGreeting() {
        StudentAttendance classUnderTest = new StudentAttendance();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        System.out.println("Hi!");
    }
}
