/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hellogradle;


import java.util.ArrayList;

public class Library {
    public int returnPassedInNumber(int num) {
        return num;
    }

    public void arrayPractice() {
      // create an array and fill it with values 1-5
      int[] foo = new int[5];
      for(int i  = 0; i < foo.length; i++) {
        foo[i] = i+1;
      }

      // create an ArrayList and print its values
      ArrayList<Integer> bar = new ArrayList<>();
      bar.add(5);
      bar.add(10);
      bar.add(15);
      for(int i = 0; i < bar.size(); i++) {
        System.out.println(bar.get(i));
      }

      // change a value at a specific index
      bar.set(0, 25);

      // create a sublist from an ArrayList
      bar.subList(0, 3); // need to assign it to a variable to keep reference!
    }
}
