/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hellogradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void returnPassedInNumberTest() {
      // Arrange
      Library sut = new Library();
      int actualOutput;

      // Act
      actualOutput = sut.returnPassedInNumber(5);

      // Assert
      // assertTrue(actualOutput == 5);
      assertEquals(5, actualOutput);
    }
}
