/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package w1d4;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testFlowerInitializes() {
        Flower flower = new Flower("Name");
        assertEquals("Name", flower.name);
        assertEquals(0, flower.getHeight());
    }

    @Test
    public void testFlowerInitializesWithHeight() {
        Flower flower = new Flower("Name", 5);
        assertEquals("Name", flower.name);
        assertEquals(5, flower.getHeight());
    }

    @Test
    public void testFlowerGrow() {
        // input
        Flower flower = new Flower("MyName");

        // action
        flower.grow();

        // assertions
        assertEquals(1, flower.getHeight());
    }

    @Test
    public void testFlowerToString() {
        Flower flower = new Flower("Sally");

        String results = flower.toString();

        assertEquals("I'm a flower and my name is: Sally", results);
    }
}
