/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aliceSearcher;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException
    {
        Path alicePath = Paths.get(".\\alice_in_wonderland.txt");
        System.out.println(alicePath.toAbsolutePath());
        Scanner scanner = null;

        String characterName = "Alice";
        scanner = new Scanner(alicePath);

        HashMap<String, Boolean> characterAppearsMap = new HashMap<String, Boolean>();

        while (scanner.hasNextLine())
        {
            String currentLine = scanner.nextLine();
            if (currentLine.contains(characterName))
            {
                characterAppearsMap.put(characterName, false);
            }
        }

        String edString1 = new String("Hi! My name is Ed!");
        String edString2 = null;

        if (characterAppearsMap.get(characterName) == null)
        {
            System.out.println(characterName + " does not appear!");
        }
        else
        {
            System.out.println(characterName + " does appear!");
        }
    }
}
