/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package w1d3a;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testGetsLengths() {
        String[] input = {"a", "ab", "abc"};
        int[] results = App.getLengths(input);

        // verify the length is correct
        assertEquals(3, results.length);

        // you can check a condition
        // but then it won't show you detailed errors in your test results
        assertTrue(3 == results.length);

        // check that the array is correct
        assertArrayEquals(new int[]{1, 2, 3}, results);
    }

    @Test
    public void testGetsLengthOfEmptyArray() {
        String[] input = {};
        int[] results = App.getLengths(input);

        assertEquals(0, results.length);
    }

    @Test
    public void testArrayContainsValue() {
        int[] input = {1, 2, 3};
        boolean results = App.arrayContains(input, 1);

        assertTrue(results);
    }

    @Test
    public void testArrayDoesNotContainsValue() {
        int[] input = {1, 2, 3};
        boolean results = App.arrayContains(input, 5);

        assertFalse(results);
    }
}
