import java.util.ArrayList;
/*
 * This Java source file was generated by the Gradle 'init' task.
 * PS: This code solves the code challenge for yesterday.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static String[] reverse(String[] stuffToReverse) {
        String[] ans = new String[stuffToReverse.length];
        for(int i = 0; i < stuffToReverse.length; i++) {
            ans[stuffToReverse.length - 1 - i] = stuffToReverse[i];
        }
        return ans;
    }

    public static ArrayList<String> reverse(ArrayList<String> stuffToReverse) {
        ArrayList<String> ans = new ArrayList<>();
        for(int i = stuffToReverse.size() - 1; i >= 0; i--) {
            ans.add(stuffToReverse.get(i));
        }
        return ans;
    }

    public static void printArrayList(ArrayList<Integer> list) {

    }
}
